apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
  annotations:
    service.kubernetes.io/ingress.class: alb
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer