apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
  annotations:
    service.kubernetes.io/ingress.class: alb
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer