apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: random-inspirational-messages
  region: ap-southeast-1

nodeGroups:
  - name: backend
    labels: backend
    instanceType: t2.micro
    desiredCapacity: 2
  - name: frontend
    labels: frontend
    instanceType: t2.micro
    desiredCapacity: 2